# serverless.yml

service: serverless-flask

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
    slimPatterns:
      - '**/*.egg-info*'
    layer: false
    noDeploy:
      - boto3
      - botocore
      - docutils
      - jmespath
      - pip
      # - nltk
      - s3transfer
      - setuptools
      # - tqdm
      - zappa
      - pytest
      # - numpy
      # - numpy.libs
      - regex

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-2

functions:
  app:
    timeout: 300
    memory: 2048
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'



package:
  exclude:
    - node_modules/**
    - venv/**