image: python:3.6.10

cache:
  paths:
    - .pip

before_script:
  - mkdir -p .pip
  - pip install -U pip
  - pip --cache-dir=.pip install -r ./server/News_Origin/requirements.txt
  - apt-get update
  - apt -y --force-yes install build-essential apt-transport-https lsb-release ca-certificates curl
  - curl -sL https://deb.nodesource.com/setup_12.x | bash -
  - apt -y --force-yes install nodejs
  - node -v
  - npm -v
  - pip --cache-dir=.pip install -r ./server/fakeNews/predictions/requirements.txt
  
stages:
    - test
    - deploy
APItest:
    stage: test
    script:
        - cd ./server/Hate_Speech/
        - pytest
        - cd ..
        - cd Click-Bait
        - pytest
        # - cd ..
        # - cd News_Origin
        # - pytest
        - cd ..
        - cd fakeNews/predictions
        - npm install -g serverless
        - npm install -g serverless-wsgi serverless-python-requirements
        - chmod +x ./slsbg.sh
        - ./slsbg.sh
APIDeploy:
    stage: deploy
    script:
        - cd ./server/Hate_Speech/
        - sls deploy
        - cd ..
        - cd Click-Bait
        - sls deploy
        - cd ..
        - cd News_Origin
        - sls deploy
        - cd ..
        - cd fakeNews/predictions
        - sls deploy