# serverless.yml

service: newsOrigin-aossie

plugins:
  - serverless-python-requirements
  - serverless-wsgi

package:
  exclude: 
    - node_modules/**

custom:
  wsgi:
    app: app.app
  pythonRequirements:
    packRequirements: true
    dockerizePip: non-linux
    slim: true
    # layer: true
    noDeploy:
      - boto3
      - botocore
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - s3transfer
      - setuptools
      - six
      - tensorboard
      - pytest
      - tensorflow
      - tqdm
      - zappa
      - pytest
      - scipy
      - scipy.libs
      - flask_swagger_ui
      - Keras
      # - numpy

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1

functions:
  app:
    handler: wsgi_handler.handler
    layers:
      # - { Ref: PythonRequirementsLambdaLayer }
      # - arn:aws:lambda:us-east-1:347034527139:layer:tf_1_11_keras:3
    timeout: 300
    memory: 2048
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'